[package]
name = "josh-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Values and evaluation for Josh"

[dependencies]
jiff.workspace = true
compact_str.workspace = true
josh-syntax.workspace = true
thiserror.workspace = true
nu-ansi-term.workspace = true
unicode-ident.workspace = true

[lints]
workspace = true
